# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vb|
    vb.gui = false
  end
  
  config.vm.define :prometheus do |prometheus|
    prometheus.vm.box = "bento/ubuntu-22.04"
    prometheus.vm.network :private_network, ip: "192.168.50.2"
    prometheus.vm.hostname = "prometheus"
  end
end
